export const PARTENZE_TRAINS = [
	{
		time: "12:07",
		destination: "Reggio Di Calabria...",
		trainName: "FR 9623",
		status: "In orario",
		bin: "18 AV",
		binType: "Effettivo",
		hasMenu: false,
	},
	{
		time: "12:10",
		destination: "Brennero Brenner",
		trainName: "REG 3850",
		status: "Partito con\n+1 MIN",
		bin: "8",
		binType: "Effettivo",
		hasMenu: true,
	},
	{
		time: "12:10",
		destination: "Venezia S. Lucia",
		trainName: "REG 3974",
		status: "Partito con\n+1 MIN",
		bin: "10",
		binType: "Effettivo",
		hasMenu: true,
	},
	{
		time: "12:12",
		destination: "Rimini",
		trainName: "REG 2499",
		status: "Partito con\n+3 MIN",
		bin: "4",
		binType: "Effettivo",
		hasMenu: true,
	},
	{
		time: "12:16",
		destination: "Brescia",
		trainName: "FR 8508",
		status: "Partito con\n+3 MIN",
		bin: "17 AV",
		binType: "Effettivo",
		hasMenu: false,
	},
	{
		time: "12:17",
		destination: "Porretta Terme",
		trainName: "REG 17721",
		status: "Partito con\n+5 MIN",
		bin: "11-PO",
		binType: "Effettivo",
		hasMenu: true,
	},
	{
		time: "12:18",
		destination: "Milano Centrale",
		trainName: "FR 9806",
		status: "In orario",
		bin: "6",
		binType: "Effettivo",
		hasMenu: false,
	},
	{
		time: "12:25",
		destination: "Lecce",
		trainName: "IC 1545",
		status: "+45 MIN",
		bin: "4",
		binType: "Programmato",
		hasMenu: false,
	},
	{
		time: "12:26",
		destination: "Milano Centrale",
		trainName: "FR 9624",
		status: "In orario",
		bin: "AV",
		binType: "Effettivo",
		hasMenu: false,
	},
	{
		time: "12:27",
		destination: "Reggio Di Calabria...",
		trainName: "FR 9607",
		status: "+17 MIN",
		bin: "AV",
		binType: "Effettivo",
		hasMenu: true,
	},
];

export const ARRIVI_TRAINS = [
	{
		time: "12:05",
		destination: "Milano Centrale",
		trainName: "FR 9623",
		status: "In orario",
		bin: "17 AV",
		binType: "Effettivo",
		hasMenu: false,
	},
	{
		time: "12:12",
		destination: "Venezia S. Lucia",
		trainName: "REG 3850",
		status: "In arrivo con\n+2 MIN",
		bin: "9",
		binType: "Effettivo",
		hasMenu: true,
	},
	{
		time: "12:15",
		destination: "Roma Termini",
		trainName: "FR 9540",
		status: "In orario",
		bin: "16 AV",
		binType: "Effettivo",
		hasMenu: false,
	},
	{
		time: "12:20",
		destination: "Firenze S. M. N.",
		trainName: "IC 1545",
		status: "+5 MIN",
		bin: "5",
		binType: "Effettivo",
		hasMenu: true,
	},
];
