export const RECENT_SEARCHES = [
	{ from: "Milano Centrale", to: "Cesena" },
	{ from: "Milano Centrale", to: "Roma Termini" },
	{ from: "Cesena", to: "Milano Centrale" },
];

export const SAVED_SEARCHES = [
	{ from: "Milano Centrale", to: "Cesena" },
	{ from: "Cesena", to: "Milano Centrale" },
];

export const STATIONS = [
	"Abano Terme",
	"Abbadia Lariana",
	"Abbasanta",
	"Abbiategrasso",
	"Acate",
	"Acciano",
	"Acerra",
	"Acireale",
	"Acqua Acetosa",
	"Acquafredda",
	"Acquamela",
	"Acquanegra Cremonese",
	"Acquappesa",
	"Acquasparta",
	"Acquaviva Casteltermini",
	"Acquaviva Delle Fonti",
	"Acquedolci-S.fratello",
	"Acqui Terme",
	"Adria",
	"Africo Nuovo",
	"Agliano Castelnuovo Calcea",
	"Agognate",
	"Agrigento Bassa",
	"Agrigento Centrale",
	"Agropoli Castellabate",
	"Aielli",
	"Airasca",
	"Airole",
	"Airuno",
	"Ala",
	"Alanno",
	"Alano Fener Valdobbiadene",
	"Alassio",
	"Alba",
	"Alba Adriatica-Nereto-Controguerra",
	"Albacina",
	"Albairate-Vermezzo",
	"Albano Di Lucania",
	"Albano Laziale",
	"Albano S.alessandro",
	"Albanova",
	"Albaredo",
	"Albate-Trecallo",
	"Albenga",
	"Albinia",
	"Albisola",
	"Albizzate Solbiate Arno",
	"Albonese",
	"Albuzzano",
	"Alcamo Diramazione",
	"Alcantara",
	"Alessandria",
	"Alfedena-Scontrone",
	"Alfonsine",
	"Ali' Terme",
	"Alice Belcolle",
	"Allerona-Castel Viscardo",
	"Alpignano",
	"Altamura",
	"Altare",
	"Altavilla Irpina",
	"Altavilla Milicia",
	"Altavilla Tavernelle",
	"Altopascio",
	"Alviano",
	"Amantea",
	"Ambivere Mapello",
	"Amendolara Oriolo",
	"Amorosi Melizzano",
	"Anagni-Fiuggi",
	"Ancona",
	"Ancona Stadio",
	"Ancona Torrette",
	"Anconetta",
	"Andora",
	"Angri",
	"Anguillara",
	"Anna'",
	"Annone Veneto",
	"Antignano",
	"Antrodoco Borgo Velino",
	"Antrodoco Centro",
	"Anversa-Villalago-Scanno",
	"Anzano Del Parco",
	"Anzio",
	"Anzio Colonia",
	"Anzola dell'Emilia",
	"Aosta",
	"Aosta Istituto",
	"Aosta Viale Europa",
	"Apice S.arcangelo Bonito",
	"Appiano",
	"Apricena",
	"Aprilia",
	"Aragona Caldare",
	"Arbia",
	"Arbostella",
	"Arce",
	"Arcene",
	"Arcisate",
	"Arcola",
	"Arcore",
	"Ardenno Masino",
	"Ardore",
	"Arechi",
	"Arena Po",
	"Arenzano",
	"Arezzo",
	"Argenta",
	"Ariano Irpino",
	"Arona",
	"Arpino",
	"Arqua'",
	"Arquata Scrivia",
	"Arsoli",
	"Artegna",
	"Arvier",
	"Ascea",
	"Asciano",
	"Asciano Monte Oliveto Maggiore",
	"Ascoli Piceno",
	"Ascoli Satriano",
	"Asola",
	"Assemini",
	"Assemini Carmine",
	"Assemini S.lucia",
	"Assisi",
	"Asti",
	"Attigliano-Bomarzo",
	"Augusta",
	"Aulla Lunigiana",
	"Avellino",
	"Aversa",
	"Avezzano",
	"Aviano",
	"Avigliana",
	"Avigliano Lucania",
	"Avio",
	"Avise",
	"Avola",
	"Badesse",
	"Badia Polesine",
	"Badolato",
	"Bagheria",
	"Bagnacavallo",
	"Bagnara",
	"Bagnaria Arsa",
	"Bagnasco",
	"Bagni Di Lucca",
	"Bagni Di Tivoli",
	"Bagnoli Agnano Terme",
	"Bagnolo Mella",
	"Baiano Di Spoleto",
	"Balangero",
	"Balanzano",
	"Baldichieri-Tigliole",
	"Balestrate",
	"Balsorano",
	"Balvano Ricigliano",
	"Balzola",
	"Bandito",
	"Baragiano-Ruoti",
	"Baranello",
	"Barberino Di Val d'Elsa",
	"Barbianello",
	"Barbiano",
	"Barcellona-Castroreale",
	"Bardonecchia",
	"Barga Gallicano",
	"Bari Centrale",
	"Bari Loseto",
	"Bari Palese Macchie",
	"Bari Parco Sud",
	"Bari S.rita",
	"Bari S.spirito",
	"Bari Torre A Mare",
	"Bari Torre Quetta",
	"Bari Villaggio Del Lavoratore",
	"Bari Zona Industriale",
	"Baricetta",
	"Barile",
	"Barletta",
	"Baronissi",
	"Basiliano",
	"Bassano Del Grappa",
	"Bassano Romano",
	"Bastia",
	"Battaglia Terme",
	"Battipaglia",
	"Baucca-Garavelle",
	"Baveno",
	"Bazzana",
	"Bazzano",
	"Beaulard",
	"Beffi",
	"Beinette",
	"Belgioioso",
	"Belgirate",
	"Bella Muro",
	"Bellano Tartavalle Terme",
	"Bellante Ripattone",
	"Bellaria",
	"Bellinzago",
	"Bellisio Solfare",
	"Belluno",
	"Belmonte Calabro",
	"Belvedere Marittimo",
	"Benevento",
	"Benevento Arco Traiano",
	"Benevento Porta Rufina",
	"Berceto",
	"Berchidda",
	"Bergamasco",
	"Bergamo",
	"Bergamo Ospedale",
	"Bernalda",
	"Besana",
	"Besnate",
	"Besozzo",
	"Bevera",
	"Bevilacqua",
	"Biagioni Lagacci",
	"Bianco",
	"Bianze'",
	"Bianzone",
	"Biassono-Lesmo Parco",
	"Bibiana",
	"Bicocca",
	"Biella S.paolo",
	"Biforco",
	"Bisceglie",
	"Bistagno",
	"Bisuschio-Viggiu'",
	"Bitetto Palo Del Colle",
	"Bitritto",
	"Bivio d'Aurisina",
	"Bogliasco",
	"Boiano",
	"Bolgheri",
	"Bologna Borgo Panigale",
	"Bologna C.le/av",
	"Bologna Centrale",
	"Bologna Corticella",
	"Bologna Fiere",
	"Bologna Mazzini",
	"Bologna S.ruffillo",
	"Bologna S.vitale",
	"Bolzano",
	"Bolzano Casanova",
	"Bolzano Novarese",
	"Bolzano Sud",
	"Bonassola",
	"Bonefro S.croce",
	"Bonferraro",
	"Bonorva",
	"Bordighera",
	"Borgaro",
	"Borghetto Parmense",
	"Borghetto S.spirito",
	"Borghetto sull'Adige",
	"Borgio Verezzi",
	"Borgo",
	"Borgo A Buggiano",
	"Borgo A Mozzano",
	"Borgo Fornari Per Voltaggio",
	"Borgo Lavezzaro",
	"Borgo Revel",
	"Borgo S.dalmazzo",
	"Borgo S.lorenzo",
	"Borgo S.lorenzo Rimorelli",
	"Borgo S.martino",
	"Borgo Ticino",
	"Borgo Val Di Taro",
	"Borgo Valsugana Centro",
	"Borgo Valsugana Est",
	"Borgo Vercelli",
	"Borgochiesanuova",
	"Borgofranco",
	"Borgolombardo",
	"Borgomanero",
	"Borgone",
	"Borgonuovo",
	"Borgoratto",
	"Borgosesia",
	"Borore",
	"Boschi S.anna",
	"Bosconero",
	"Botricello",
	"Bottenicco",
	"Bova Marina",
	"Bovalino",
	"Bovino Deliceto",
	"Bovolone",
	"Bozzolo",
	"Bra",
	"Bracciano",
	"Bragno",
	"Brancaleone",
	"Brandizzo",
	"Breil Sur Roya",
	"Brenna-Alzate",
	"Brennero",
	"Brescia",
	"Bressana Argine",
	"Bressana Bottarone",
	"Bressanone",
	"Briatico",
	"Bricherasio",
	"Brindisi",
	"Brindisi Cittadella Della Ricerca",
	"Brindisi Perrino",
	"Briona",
	"Brisighella",
	"Brolo Ficarra",
	"Broni",
	"Bronzolo",
	"Brozolo",
	"Brucoli",
	"Brunico",
	"Brunico Nord",
	"Bruno",
	"Bruzolo Di Susa",
	"Buccino S.gregorio Magno",
	"Bucine",
	"Budoia Polcenigo",
	"Bugnara",
	"Buonconvento",
	"Buronzo",
	"Busa Di Vigonza",
	"Busalla",
	"Busca",
	"Busche Lentiai Mel",
	"Busseto",
	"Bussi",
	"Bussoleno",
	"Busto Arsizio",
	"Buttafava",
	"Buttapietra",
	"Buttrio",
	"Ca` Di Boschetti",
	"Cadeo",
	"Cagliari",
	"Cagliari Elmas",
	"Cagliari S.gilla",
	"Cairo Montenotte",
	"Cala Sabina",
	"Calalzo Pieve Cadore Cortina",
	"Calamandrana",
	"Calatabiano",
	"Calatafimi",
	"Calceranica",
	"Calde'",
	"Calderara-Bargellino",
	"Caldonazzo",
	"Calenzano",
	"Calliano",
	"Calolziocorte Olginate",
	"Calopezzati",
	"Caltagirone",
	"Caltanissetta Centrale",
	"Caltanissetta Xirbi",
	"Caltignaga",
	"Calusco",
	"Caluso",
	"Calvisano",
	"Camaiore Lido Capezzano",
	"Cambiano Santena",
	"Camerano Aspio",
	"Cammarata S.giovanni Gemini",
	"Camnago-Lentate",
	"Camogli S.fruttuoso",
	"Campagna Serre Persano",
	"Campello Sul Clitunno",
	"Campiglia Marittima",
	"Campo Di Carne",
	"Campo Di Giove",
	"Campo Di Giove-Monte Maiella",
	"Campo Di Trens",
	"Campo Ligure-Masone",
	"Campobasso",
	"Campobello Di Mazara",
	"Campobello Ravanusa",
	"Campodarsego",
	"Campofelice",
	"Campofranco",
	"Campoleone",
	"Campolieto Monacilioni",
	"Campomarino",
	"Campomigliaio",
	"Campora S.giovanni Serra Aiello",
	"Camporgiano",
	"Camposampiero",
	"Camposanto",
	"Camucia Cortona",
	"Canaro",
	"Cancelliera",
	"Cancello",
	"Cancello Arnone",
	"Candelo",
	"Candia Canavese",
	"Candia Lomellina",
	"Candiolo",
	"Canegrate",
	"Canelli",
	"Canetra",
	"Canicatti'",
	"Canistro",
	"Canne Della Battaglia",
	"Canneto sull'Oglio",
	"Cannizzaro",
	"Canosa Di Puglia",
	"Canoscio",
	"Cansano",
	"Cansano Scavi Di Ocriticum",
	"Cantello Gaggiolo",
	"Cantu'",
	"Cantu'-Cermenate",
	"Caorso",
	"Capaccio Roccadaspide",
	"Capaci",
	"Capalbio",
	"Capannelle",
	"Capistrello",
	"Capo Bonifati",
	"Capo d'Orlando-Naso",
	"Capo Spartivento",
	"Capocroce",
	"Cappelle-Magliano",
	"Capralba",
	"Capranica-Sutri",
	"Capriati Al Volturno",
	"Capriva",
	"Capua",
	"Carate-Calo'",
	"Caravaggio",
	"Carbona",
	"Carbonia Serbariu",
	"Carbonia Stato",
	"Carentino",
	"Cariati",
	"Carimate",
	"Carini",
	"Carini Torre Ciachea",
	"Carmagnola",
	"Carmignano Di Brenta",
	"Carnate Usmate",
	"Carnia",
	"Caronia",
	"Carovigno",
	"Carovilli-Roccasicura",
	"Carpane'-Valstagna",
	"Carpi",
	"Carpignano Sesia",
	"Carpinone",
	"Carrara Avenza",
	"Carrito-Ortona",
	"Carruba",
	"Carsoli",
	"Casabianca",
	"Casacalenda Guardialfiera",
	"Casalbordino Pollutri",
	"Casalbuttano",
	"Casale Monferrato",
	"Casalecchio Di Reno",
	"Casalecchio Garibaldi",
	"Casaleggio",
	"Casaletto Vaprio",
	"Casalmaggiore",
	"Casalnuovo",
	"Casalpusterlengo",
	"Casarsa",
	"Cascina",
	"Caselle Torinese",
	"Caserta",
	"Casino Di Terra",
	"Casletto-Rogeno",
	"Casorate Sempione",
	"Casoria-Afragola",
	"Cassago-Nibionno-Bulciago",
	"Cassano d'Adda",
	"Cassine",
	"Cassino",
	"Cassola",
	"Castagnaro",
	"Castagneto Carducci-Donoratico",
	"Castagno",
	"Castagnole Delle Lanze",
	"Casteggio",
	"Castel d'Ario",
	"Castel Di Sangro",
	"Castel Gandolfo",
	"Castel Lagopesole",
	"Castel Madama",
	"Castel S.angelo",
	"Castel S.giorgio Roccapiemonte",
	"Castel S.giovanni",
	"Castel S.pietro Terme",
	"Castelbolognese-Riolo Terme",
	"Casteldaccia",
	"Casteldarne",
	"Casteldebole",
	"Castelferretti-Falconara Aeroporto",
	"Castelfiorentino",
	"Castelfranco Emilia",
	"Castelfranco Veneto",
	"Castelguelfo",
	"castell'Alfero",
	"Castellalto Canzano",
	"Castellammare Del Golfo",
	"Castellammare Di Stabia",
	"Castellaneta",
	"Castellaneta Marina",
	"Castelleone",
	"Castelletto Ticino",
	"Castellina In Chianti-Monteriggioni",
	"Castello d'Annone",
	"Castello Di Godego",
	"Castellucchio",
	"Castelmaggiore",
	"Castelnuovo Belbo",
	"Castelnuovo Berardenga",
	"Castelnuovo Del Garda",
	"Castelnuovo Di Garfagnana",
	"Castelplanio Cupramontana",
	"Castelraimondo Camerino",
	"Castelrosso",
	"Castelvecchio Pascoli",
	"Castelvetrano",
	"Castelvetro",
	"Castiglion Del Lago",
	"Castiglion Fiorentino",
	"Castiglioncello",
	"Castiglione Cosentino",
	"Castione Andevenno",
	"Castione Dei Marchesi",
	"Castro-Pofi-Vallecorsa",
	"Castronno",
	"Catania Acquicella",
	"Catania Aeroporto Fontanarossa",
	"Catania Centrale",
	"Catanzaro",
	"Catanzaro Lido",
	"Catenanuova-Centuripe",
	"Cattolica S.giovanni Gabicce",
	"Caulonia",
	"Cava Carbonara",
	"Cava Dei Tirreni",
	"Cava Tigozzi",
	"Cavagnolo Brusasco",
	"Cavalleggeri Aosta",
	"Cavallermaggiore",
	"Cavanella d'Adige",
	"Cavaria Oggiona Ierago",
	"Cavazzale",
	"Cavi",
	"Ceccano",
	"Cecchina",
	"Cecina",
	"Cefalu'",
	"Ceggia",
	"Celano-Ovindoli",
	"Celle",
	"Celle Bulgheria Roccagloriosa",
	"Cengio",
	"Centallo",
	"Centola-Palinuro-Marina Di Camerota",
	"Ceprano-Falvaterra",
	"Cerbara",
	"Cerchio",
	"Cerda",
	"Cerea",
	"Ceregnano",
	"Ceriale",
	"Cerignola Campagna",
	"Cernusco-Merate",
	"Cerqueto",
	"Cerreto d'Esi",
	"Certaldo",
	"Certosa Di Pavia",
	"Cervia-Milano Marittima",
	"Cervignano-Aquileia-Grado",
	"Cesano Boscone",
	"Cesano Di Roma",
	"Cesena",
	"Cesenatico",
	"Cesi",
	"Cetraro",
	"Ceva",
	"Chatillon-Saint-Vincent",
	"Chianche Ceppaloni",
	"Chiaravalle",
	"Chiari",
	"Chiasso",
	"Chiavari",
	"Chiavenna",
	"Chieri",
	"Chieti",
	"Chieti-Madonna Delle Piane",
	"Chieuti Serracapriola",
	"Chignolo Po",
	"Chioggia",
	"Chiomonte",
	"Chiuduno",
	"Chiuro",
	"Chiusa",
	"Chiusano Cossombrato",
	"Chiusi-Chianciano Terme",
	"Chivasso",
	"Ciampino",
	"Cinisi Terrasini",
	"Cirie'",
	"Ciro'",
	"Cisano Caprino Bergamasco",
	"Cismon Del Grappa",
	"Cisterna Di Latina",
	"Cisternino",
	"Citta' Di Castello",
	"Citta` Di Castello - Fornace",
	"Citta` Di Castello - Zona Industriale",
	"Cittadella",
	"Cittaducale",
	"Civate",
	"Cividale Del Friuli",
	"Cividate-Calcio",
	"Civita Castellana-Magliano",
	"Civita d'Antino-Morino",
	"Civitanova Marche-Montegranaro",
	"Civitavecchia",
	"Civitella Paganico",
	"Civitella Roveto",
	"Classe",
	"Coccaglio",
	"Cocconato",
	"Cocullo",
	"Codogno",
	"Codola",
	"Codroipo",
	"Cogoleto",
	"Colfelice",
	"Colico",
	"Collarmele",
	"Colle Isarco",
	"Colle Mattia",
	"Collecchio",
	"Colleferro-Segni-Paliano",
	"Collegno",
	"Collevalenza R.r.",
	"Collevecchio-Poggio Sommavilla",
	"Colli Del Tronto",
	"Colli Di Monte Bove",
	"Cologne",
	"Colonna Galleria",
	"Colorno",
	"Comignago",
	"Comiso",
	"Como Camerlata",
	"Como S.giovanni",
	"Compiobbi",
	"Compre S.vincenzo",
	"Condofuri",
	"Condove-Chiusa S.michele",
	"Conegliano",
	"Conselice",
	"Contea Londa",
	"Contesse",
	"Contigliano",
	"Contursi Terme",
	"Corbetta-S.stefano Ticino",
	"Corbezzi",
	"Cordovado Sesto",
	"Corigliano Calabro",
	"Cormons",
	"Corniglia",
	"Cornino",
	"Cornuda",
	"Coronella",
	"Corridonia Mogliano",
	"Corsano",
	"Corsico",
	"Corteolona",
	"Cosenza",
	"Cosio Traona",
	"Cossato",
	"Costa",
	"Costa Masnaga",
	"Costigliole (motta Di)",
	"Costigliole D`asti",
	"Costigliole Saluzzo",
	"Cotignola",
	"Crema",
	"Cremona",
	"Crescentino",
	"Crespino Del Lamone",
	"Cressa Fontaneto",
	"Crevalcore",
	"Cropani",
	"Crotone",
	"Crucoli",
	"Cucciago",
	"Cuneo",
	"Cuneo Gesso",
	"Cunico Scandeluzza",
	"Cupone",
	"Cupramarittima",
	"Cureggio",
	"Curinga",
	"Cusano",
	"Cutro",
	"Cuzzago (mi)",
	"Cuzzago (no)",
	"Decimomannu",
	"Dego",
	"Deiva Marina",
	"Delebio",
	"Derby",
	"Deruta",
	"Dervio",
	"Desenzano Del Garda-Sirmione",
	"Desio",
	"Diamante Buonvicino",
	"Diano",
	"Dicomano",
	"Diecimo-Pescaglia",
	"Dittaino",
	"Dobbiaco",
	"Dolo",
	"Domegliara-S.ambrogio",
	"Domodossola",
	"Donnafugata",
	"Donnas",
	"Dorio",
	"Dormelletto",
	"Dormelletto Paese",
	"Dossobuono",
	"Dubino",
	"Duca d'Aosta",
	"Dueville",
	"Duomo Via Vernieri",
	"Eboli",
	"Eca Nasago`",
	"Egna-Termeno",
	"Ellera Corciano",
	"Elmas Aeroporto",
	"Empoli",
	"Enas",
	"Enna",
	"Equi Terme",
	"Este",
	"Europa Pes",
	"Fabriano",
	"Fabriano Ca' Maiano",
	"Fabro-Ficulle",
	"Fae'-Fortogna",
	"Faenza",
	"Fagare'",
	"Fagnano Campana",
	"Falciano-Mondragone-Carinola",
	"Falconara",
	"Falconara Marittima",
	"Falconara Stadio",
	"Falcone",
	"Falerna",
	"Fanciullata",
	"Fanna-Cavasso",
	"Fano",
	"Fanzolo",
	"Fara",
	"Fara Sabina-Montelibretti",
	"Fasano",
	"Favazzina",
	"Federico",
	"Felegara-S.andrea Bagni",
	"Feletto",
	"Felizzano",
	"Feltre",
	"Ferentino-Supino",
	"Ferrandina Scalo-Matera",
	"Ferrania",
	"Ferrara",
	"Ferrera Lomellina",
	"Ferruzzano",
	"Ficarazzi",
	"Fidene",
	"Fidenza",
	"Fiera",
	"Fiera Di Roma",
	"Fiesole Caldine",
	"Figline Valdarno",
	"Filattiera",
	"Filiano",
	"Finale Ligure Marina",
	"Fiorenzuola",
	"Firenze Campo Marte",
	"Firenze Castello",
	"Firenze Rifredi",
	"Firenze Rovezzano",
	"Firenze S. M. N.",
	"Firenze Santa Maria Novella",
	"Firenze Statuto",
	"Fisciano",
	"Fiumara Gazzi",
	"Fiumefreddo Bruzio",
	"Fiumefreddo Di Sicilia",
	"Fiumelatte",
	"Fiumetorto",
	"Fiumicino Aeroporto",
	"Fivizzano Rometta-Soliera",
	"Fivizzano-Gassano",
	"Foggia",
	"Fognano",
	"Foligno",
	"Follonica",
	"Fondi-Sperlonga",
	"Fontan Saorge",
	"Fontana Liri",
	"Fontana Liri Inferiore",
	"Fontanafredda",
	"Fontanarosa-Cervaro",
	"Fontane Bianche",
	"Fontanetto Po",
	"Fontaniva",
	"Fontecchio",
	"Forenza",
	"Forgaria Bagni Anduins",
	"Forli'",
	"Forlimpopoli-Bertinoro",
	"Formia-Gaeta",
	"Fornaci Di Barga",
	"Fornovo",
	"Forte Dei Marmi-Seravezza-Querceta",
	"Fortezza",
	"Fosciandora-Ceserana",
	"Fossacesia-Torino Di Sangro",
	"Fossalta Di Piave",
	"Fossano",
	"Fossato Di Vico Gubbio",
	"Fragneto Monforte",
	"Framura",
	"Francavilla Al Mare",
	"Francavilla Angitola-Filadelfia",
	"Francavilla Fontana",
	"Franciosa",
	"Frascati",
	"Frasso",
	"Frasso Telesino-Dugenta",
	"Fratta",
	"Fratta Todina",
	"Frattamaggiore-Grumo",
	"Fratte",
	"Fratte Centro",
	"Fratte Villa Comunale",
	"Frosinone",
	"Frugarolo Boscomarengo",
	"Funo Centergross",
	"Furapane",
	"Furci",
	"Fuscaldo",
	"Gaggiano",
	"Gaggio Porta Est",
	"Gagliole",
	"Gaibanella",
	"Gaifana",
	"Galati",
	"Gallarate",
	"Gallese In Teverina",
	"Galliera",
	"Galliera Veneta Tombolo",
	"Gambettola",
	"Gambolo'-Remondo'",
	"Garbagna",
	"Garessio",
	"Gargazzone",
	"Garlasco",
	"Gatteo A Mare",
	"Gattinara",
	"Gavignano Sabino",
	"Gavorrano",
	"Gazzada Schianno Morazzone",
	"Gazzo Di Bigarello",
	"Gazzo Pieve S.giacomo",
	"Gela",
	"Gela-Anic",
	"Gemelli",
	"Gemona Del Friuli",
	"Genga S.vittore Terme",
	"Genova Acquasanta",
	"Genova Bolzaneto",
	"Genova Borzoli",
	"Genova Brignole",
	"Genova Cornigliano",
	"Genova Costa Di Sestri Ponente",
	"Genova Granara",
	"Genova Nervi",
	"Genova Pegli",
	"Genova Piazza Principe",
	"Genova Piazza Principe Sotterranea",
	"Genova Pontedecimo",
	"Genova Pra",
	"Genova Quarto Dei Mille",
	"Genova Quinto Al Mare",
	"Genova Rivarolo",
	"Genova S.biagio",
	"Genova Sampierdarena",
	"Genova Sestri Ponente Aeroporto",
	"Genova Sturla",
	"Genova Vesima",
	"Genova Via Di Francia",
	"Genova Voltri",
	"Germagnano",
	"Ghedi",
	"Ghemme",
	"Ghislarengo",
	"Ghivizzano-Coreglia",
	"Giachery",
	"Giampilieri",
	"Giarole",
	"Giarre Riposto",
	"Giave",
	"Ginosa",
	"Gioia Del Colle",
	"Gioia Tauro",
	"Gioiosa Jonica",
	"Giojosa Marea",
	"Giovinazzo",
	"Giugliano Qualiano",
	"Giulianova",
	"Gizzeria Lido",
	"Glorie",
	"Godo",
	"Golfo Aranci",
	"Gonzaga-Reggiolo",
	"Gorgo Al Monticano",
	"Goriano Sicoli",
	"Gorizia Centrale",
	"Gozzano",
	"Gragnola",
	"Grammichele",
	"Granaiolo",
	"Granarolo Faentino",
	"Grassano-Garaguso-Tricarico",
	"Gravellona Toce",
	"Gravina In Puglia",
	"Greccio",
	"Gricignano-Teverola",
	"Grignasco",
	"Grigno",
	"Grisignano Di Zocco",
	"Grisolia S.maria",
	"Grizzana",
	"Gropello Cairoli",
	"Grosseto",
	"Grottaglie",
	"Grottammare",
	"Grotte",
	"Grotte S.stefano",
	"Grugliasco",
	"Grumello Del Monte",
	"Grumo Appula",
	"Gualdo Tadino",
	"Guardavalle",
	"Guardia Mangano S.venerina",
	"Guardia Piemontese Terme",
	"Guidonia-Montecelio-S.angelo",
	"Hone-Bard",
	"Igea Marina",
	"Iglesias",
	"Il Neto",
	"Ilci-Pian Dei Mori",
	"Imola",
	"Imperia",
	"Incisa",
	"Incisa Scapaccino",
	"Incoronata",
	"Induno Olona",
	"Ipogeo Degli Ottavi",
	"Isernia",
	"Isola D`asti",
	"Isola Del Cantone",
	"Isola Della Scala",
	"Isola Delle Femmine",
	"Isola Liri",
	"Isoletta-S.giovanni Incarico",
	"Ispica",
	"Istrana",
	"Itri",
	"Ivrea",
	"Jesi",
	"Joppolo",
	"l'Aquila",
	"l'Aquila Campo Di Pile",
	"l'Aquila S.gregorio",
	"l'Aquila Sassa Nucleo Sviluppo",
	"La Brigue",
	"La Dogana",
	"La Fiora",
	"La Giustiniana",
	"La Rustica Citta'",
	"La Rustica Uir",
	"La Salle",
	"La Spezia Centrale",
	"La Spezia Migliarina",
	"La Storta",
	"Labico",
	"Labro Moggio",
	"Ladispoli-Cerveteri",
	"Laigueglia",
	"Laives",
	"Lama",
	"Lama Di Reno",
	"Lambrinia",
	"Lamezia Terme Centrale",
	"Lamezia Terme Nicastro",
	"Lamezia Terme Sambiase",
	"Lana-Postal",
	"Lancenigo",
	"Lanuvio",
	"Lanzara Fimiani",
	"Lanzo Torinese",
	"Larino",
	"Lascari",
	"Lastra A Signa",
	"Laterina",
	"Latiano",
	"Latina",
	"Latisana Lignano-Bibione",
	"Lauriano",
	"Lavagna",
	"Laveno Mombello",
	"Lavezzola",
	"Lavis",
	"Le Cure",
	"Le Piagge",
	"Lecce",
	"Lecco",
	"Lecco Maggianico",
	"Leggiuno Monvalle",
	"Legnago",
	"Legnano",
	"Lendinara",
	"Lentini",
	"Lentini Diramazione",
	"Leonforte-Pirato",
	"Lercara Diramazione",
	"Lerino",
	"Lesa",
	"Lesegno",
	"Lesmo",
	"Letojanni",
	"Levada",
	"Levanto",
	"Levata",
	"Levate",
	"Levico Terme",
	"Licata",
	"Lido Di Classe-Lido Di Savio",
	"Lido Di Lavinio",
	"Lierna",
	"Limone",
	"Lison",
	"Lissone-Muggio'",
	"Livorno Centrale",
	"Livorno Ferraris",
	"Loano",
	"Locate Triulzi",
	"Locri",
	"Lodi",
	"Lolli",
	"Lomello",
	"Lonato",
	"Longarone Zoldo",
	"Longobardi",
	"Lonigo",
	"Loreo",
	"Loreto",
	"Lucca",
	"Lugo",
	"Luino",
	"Lumignacco",
	"Lunghezza",
	"Luni",
	"Luserna S. Giovanni",
	"Maccarese-Fregene",
	"Macerata",
	"Macerata Fontescodella",
	"Macerata Universita'",
	"Macherio Sovico",
	"Macherio-Canonica",
	"Macomer",
	"Maddaloni Inferiore",
	"Madignano",
	"Madonna Del Pilone",
	"Maerne Di Martellago",
	"Magenta",
	"Magione",
	"Magliana",
	"Magliano Crava Morozzo",
	"Magre'-Cortaccia",
	"Maleo",
	"Maltignano Del Tronto",
	"Manarola",
	"Mandatoriccio Campana",
	"Mandello Del Lario",
	"Manerbio",
	"Manfredonia",
	"Manfredonia Ovest",
	"Maniago",
	"Manoppello",
	"Manta",
	"Mantova",
	"Mantova Frassine",
	"Manzano",
	"Manziana-Canale Monterano",
	"Marano Ticino",
	"Marano Vicentino",
	"Maratea",
	"Marausa",
	"Marcaria",
	"Marcellina-Palombara",
	"Marcellina-Verbicaro-Orsomarso",
	"Marcellinara",
	"Marcianise",
	"Marconi",
	"Marechiaro",
	"Maredolce",
	"Margarita",
	"Marianopoli",
	"Marina Di Cerveteri",
	"Marina Di Maratea",
	"Marina Di S.lorenzo",
	"Marinella",
	"Marino Del Tronto-Folignano",
	"Marino Laziale",
	"Marmore",
	"Marotta-Mondolfo",
	"Marradi-Palazzuolo Sul Senio",
	"Marrubiu-Terralba-Arborea",
	"Marsala",
	"Marsciano",
	"Martinsicuro",
	"Marzabotto",
	"Marzocca",
	"Mascali",
	"Massa Centro",
	"Massa Martana",
	"Massafra",
	"Massalombarda",
	"Massarosa Bozzano",
	"Matelica",
	"Mathi",
	"Matrice-Montagano-S.giovanni In Galdo",
	"Mazara Del Vallo",
	"Mede",
	"Medesano",
	"Meduno",
	"Meina",
	"Melano Marischio",
	"Mele",
	"Melegnano",
	"Melfi",
	"Melito Di Porto Salvo",
	"Melzo",
	"Meolo",
	"Merana",
	"Merano",
	"Merano-Maia Bassa",
	"Mercatello",
	"Mercato S.severino",
	"Mercenasco",
	"Mergozzo",
	"Mesagne",
	"Messina Centrale",
	"Mestrino",
	"Metaponto",
	"Mezzani Rondani",
	"Mezzano",
	"Mezzocorona",
	"Mignano Monte Lungo",
	"Milano Bovisa Politecnico",
	"Milano Centrale",
	"Milano Certosa",
	"Milano Dateo",
	"Milano Forlanini",
	"Milano Greco Pirelli",
	"Milano Lambrate",
	"Milano Lancetti",
	"Milano Porta Garibaldi",
	"Milano Porta Garibaldi Sotterranea",
	"Milano Porta Genova",
	"Milano Porta Venezia",
	"Milano Porta Vittoria",
	"Milano Repubblica",
	"Milano Rogoredo",
	"Milano Romolo",
	"Milano S.cristoforo",
	"Milano Scalo Romana",
	"Milano Tibaldi Universita' Bocconi",
	"Milano Villapizzone",
	"Milazzo",
	"Mileto",
	"Mili Marina",
	"Militello",
	"Minervino Murge",
	"Minturno-Scauri",
	"Minucciano-Pieve-Casola",
	"Mira Mirano",
	"Miradolo Terme",
	"Miramare",
	"Mirandola",
	"Mirto Crosia",
	"Misano Adriatico",
	"Modane",
	"Modane Fourneaux",
	"Modena",
	"Modica",
	"Modugno",
	"Mogliano Veneto",
	"Moiana",
	"Moimacco",
	"Mola Di Bari",
	"Molare",
	"Molfetta",
	"Molina-Castelvecchio Subequo",
	"Molino Del Pallone",
	"Molteno",
	"Mombaldone-Roccaverano",
	"Mombaruzzo",
	"Momo",
	"Monasterace-Stilo",
	"Moncalieri",
	"Moncalieri Sangone",
	"Moncalvo",
	"Mondovi`",
	"Moneglia",
	"Monfalcone",
	"Mongardino",
	"Mongrassano-Cervicati",
	"Monguelfo-Valle Di Casies",
	"Monopoli",
	"Monsampolo Del Tronto",
	"Monselice",
	"Montagnana",
	"Montaguto Panni",
	"Montale Agliana",
	"Montalto Di Castro",
	"Montanaro",
	"Monte Antico",
	"Monte S.biagio-Terracina Mare",
	"Montebello",
	"Montebelluna",
	"Montecalvo-Buonalbergo-Casalbore",
	"Montecarlo S.salvatore",
	"Montecarotto-Castelbellino",
	"Montecastelli",
	"Montecastelli Ponte Tevere",
	"Montecastrilli",
	"Montecatini Centro",
	"Montecatini Terme-Monsummano",
	"Montechiaro D`asti",
	"Montechiaro Denice",
	"Montecorona",
	"Montecorvino",
	"Montecosaro",
	"Montefiascone",
	"Montefredane",
	"Montegiordano",
	"Montegrosso",
	"Montello Gorlago",
	"Montelupo Capraia",
	"Montemaggiore Belsito",
	"Montemarciano",
	"Montenero Petacciato",
	"Montepaone-Montauro",
	"Montepescali",
	"Monteprandone",
	"Montepulciano",
	"Montereale Valcellina",
	"Monteroni d'Arbia",
	"Monterosso",
	"Monterosso Marche",
	"Monterotondo-Mentana",
	"Montesanto",
	"Montesilvano",
	"Monteu Da Po",
	"Montevarchi Terranuova",
	"Monti Telti",
	"Monticelli d'Ongina",
	"Monticello D`alba",
	"Montiglio Murisengo",
	"Montirone",
	"Montoro Forino",
	"Montoro Superiore",
	"Montorsi",
	"Monza",
	"Monza Sobborghi",
	"Monzone-Monte Dei Bianchi-Isolano",
	"Monzuno-Vado",
	"Morano Sul Po",
	"Morbegno",
	"Morengo Bariano",
	"Morgex",
	"Mori",
	"Mornago Cimbro",
	"Morolo",
	"Morrea-Castronovo-Rendinara",
	"Morrovalle Monte S.giusto",
	"Mortara",
	"Mosciano S.angelo",
	"Mossa",
	"Motta Di Livenza",
	"Motta S.damiano",
	"Motta S.giovanni Lazzaro",
	"Mozia-Birgi",
	"Mozzecane",
	"Mulinetti",
	"Muratella",
	"Murlo",
	"Musiano-Pian Di Macina",
	"Mussotto",
	"Muzzana Del Turgnano",
	"Napoli Afragola",
	"Napoli Campi Flegrei",
	"Napoli Centrale",
	"Napoli Gianturco",
	"Napoli Mergellina",
	"Napoli Montesanto",
	"Napoli Piazza Amedeo",
	"Napoli Piazza Cavour",
	"Napoli Piazza Garibaldi",
	"Napoli Piazza Leopardi",
	"Napoli S.giovanni Barra",
	"Narni Amelia",
	"Navacchio",
	"Neive",
	"Nepezzano-Piano d'Accio",
	"Nera Montoro",
	"Nettuno",
	"Nibbia",
	"Niccone",
	"Nichelino",
	"Nicorvo",
	"Nicotera",
	"Niscemi",
	"Nizza Di Sicilia",
	"Nizza Monferrato",
	"Noale-Scorze'",
	"Nocera Inferiore",
	"Nocera Inferiore Mercato",
	"Nocera Superiore",
	"Nocera Tirinese",
	"Nocera Umbra",
	"Noceto",
	"Nogara",
	"Nola",
	"Nole",
	"None",
	"Notaresco",
	"Noto",
	"Nova Siri Rotondella",
	"Novara",
	"Novara-Montalbano-Furnari",
	"Novate-Mezzola",
	"Novi Ligure",
	"Nozzano",
	"Nucetto",
	"Nuovo Salario",
	"Nus",
	"Occhiobello",
	"Oderzo",
	"Offida Castel Di Lama",
	"Oggiono",
	"Ognina Pes",
	"Olbia",
	"Olbia Terranova",
	"Olcenengo",
	"Olcio",
	"Oleggio",
	"Olevano",
	"Olgiata",
	"Olgiate-Calco-Brivio",
	"Oliveri Tindari",
	"Olivetta S.michele",
	"Olmeneta",
	"Olmi Spercenigo",
	"Omegna",
	"Omegna-Crusinallo",
	"Omignano Salento",
	"Ora",
	"Orbetello-Monte Argentario",
	"Ordona",
	"Oria",
	"Oricola-Pereto",
	"Orio Litta",
	"Oriolo",
	"Oristano",
	"Ormea",
	"Ornavasso",
	"Orsa",
	"Orsago",
	"Orsara Di Puglia",
	"Orta Miasino",
	"Ortanova",
	"Orte",
	"Ortona",
	"Orvieto",
	"Oschiri",
	"Osimo Castelfidardo",
	"Osnago",
	"Osoppo",
	"Ospedaletto Euganeo",
	"Ospedaletto Lodigiano",
	"Ospitale Di Cadore",
	"Ospitaletto Mantovano",
	"Ospitaletto Travagliato",
	"Osteria Nuova",
	"Ostia Parmense",
	"Ostiglia",
	"Ostuni",
	"Ottavia",
	"Oulx Cesana Claviere Sestriere",
	"Ovada",
	"Oviglio",
	"Ozieri Chilivani",
	"Ozzano dell'Emilia",
	"Ozzano Monferrato",
	"Ozzano Taro",
	"Pabillonis",
	"Pace Del Mela",
	"Paceco",
	"Paderno Robbiate",
	"Padiglione",
	"Padova",
	"Paduli Sul Calore",
	"Paese",
	"Paese Castagnole",
	"Paestum",
	"Pagani",
	"Paganica",
	"Palagianello",
	"Palagiano Chiatona",
	"Palagiano Mottola",
	"Palazzaccia",
	"Palazzo Reale-Orleans",
	"Palazzolo Dello Stella",
	"Palazzolo sull'Oglio",
	"Palazzolo Vercellese",
	"Palena",
	"Palermo Aeroporto",
	"Palermo Brancaccio",
	"Palermo Cardillo",
	"Palermo Centrale",
	"Palermo De Gasperi",
	"Palermo Francia",
	"Palermo Guadagna",
	"Palermo La Malfa",
	"Palermo Liberta'",
	"Palermo Notarbartolo",
	"Palermo Politeama Pes",
	"Palermo Porto",
	"Palermo S.lorenzo",
	"Palermo Sferracavallo",
	"Palermo Tommaso Natale",
	"Palermo Vespri",
	"Palestro",
	"Palidano",
	"Palizzi",
	"Pallanzeno",
	"Palma S.gennaro",
	"Palmanova",
	"Palmi",
	"Palmiro Togliatti",
	"Palombina",
	"Pantanella",
	"Pantiere Di Castelbellino",
	"Paola",
	"Papiano",
	"Parabiago",
	"Paratico Sarnico",
	"Parco Leonardo",
	"Parghelia",
	"Parma",
	"Parona Lomellina",
	"Partinico",
	"Passignano Sul Trasimeno",
	"Pastena",
	"Paterno-S.pelino",
	"Patti-S.piero Patti",
	"Paulilatino",
	"Pavia",
	"Pavia Porta Garibaldi",
	"Pavona",
	"Pc Caldiero",
	"Pc Dolce'",
	"Pc Meana",
	"Pedaso",
	"Pederobba Cavaso Possagno",
	"Pellezzano",
	"Penango",
	"Perarolo Di Cadore",
	"Perca-Plan De Corones",
	"Pergine",
	"Pergola",
	"Peri",
	"Perugia",
	"Perugia Capitini",
	"Perugia Pallotta",
	"Perugia Ponte S.giovanni",
	"Perugia S.anna",
	"Perugia Silvestrini",
	"Perugia Universita'",
	"Pesaro",
	"Pescara",
	"Pescara Porta Nuova",
	"Pescara S.marco",
	"Pescara Tribunale",
	"Peschiera Del Garda",
	"Pescia",
	"Pescina",
	"Pescocanale",
	"Pescolanciano-Chiauci",
	"Pessione",
	"Petrosino Strasatti",
	"Pettenasco",
	"Pettorano Sul Gizio",
	"Piacenza",
	"Piadena",
	"Pian Del Mugnone",
	"Pian Di Porto",
	"Pian Di Venola",
	"Piana",
	"Piana Bella Di Montelibretti",
	"Pianerottolo d'Ariano",
	"Pianfei",
	"Piano d'Orta Bolognano",
	"Piano Orizzontale Dei Giovi",
	"Pianoro",
	"Pianzano",
	"Piazza Al Serchio",
	"Picanello",
	"Picerno",
	"Piedimonte-Villa S.lucia-Aquino",
	"Piedimulera",
	"Pierantonio",
	"Pietra Ligure",
	"Pietrabissara",
	"Pietragalla",
	"Pietrarsa-S.giorgio A Cremano",
	"Pietrasanta",
	"Pietrelcina",
	"Pieve Albignola",
	"Pieve Emanuele",
	"Pieve Ligure",
	"Pieve Vergonte",
	"Pievetta",
	"Pignataro Maggiore",
	"Pinarolo Po",
	"Pinerolo",
	"Pinerolo Olimpica",
	"Pineto Atri",
	"Pinzano",
	"Pioltello Limito",
	"Piombino",
	"Piombino Dese",
	"Piombino Marittima",
	"Piona",
	"Pioppe Di Salvaro",
	"Piraineto",
	"Pisa Centrale",
	"Pisa/binari Pisa S.rossore",
	"Piscille",
	"Piscina Di Pinerolo",
	"Pisciotta Palinuro",
	"Pisticci",
	"Pistoia",
	"Pistoia Ovest",
	"Piteccio",
	"Pizzale-Lungavilla",
	"Pizzighettone",
	"Pizzo",
	"Ploaghe",
	"Pm Chambave",
	"Pm Eccellente",
	"Pm Feroleto Antico Pianopoli",
	"Pm Gabella Grande",
	"Pm Isola Capo Rizzuto",
	"Pm Ispra",
	"Pm Montalto Rose",
	"Pm Montjovet",
	"Pm Quart",
	"Pm S.leonardo Di Cutro",
	"Pm S.mauro La Bruca",
	"Pm Thurio",
	"Pocapaglia",
	"Poggibonsi-S.gimignano",
	"Poggio Fidoni",
	"Poggio Imperiale",
	"Poggio Mirteto",
	"Poggio Renatico",
	"Poggio Rusco",
	"Poggio-Careggine-Vagli",
	"Poggiridenti-Tresivio-Piateda",
	"Polesella",
	"Policastro Bussentino",
	"Policoro Tursi",
	"Polignano A Mare",
	"Pollenza",
	"Pollina-S.mauro Castelverde",
	"Pomezia-S.palomba",
	"Pompei",
	"Pont-Saint-Martin",
	"Pontassieve",
	"Ponte A Elsa",
	"Ponte A Moriano",
	"Ponte A Tressa",
	"Ponte Albanito",
	"Ponte Casalduni",
	"Ponte d'Adda",
	"Ponte d'Adige",
	"Ponte Della Venturina",
	"Ponte Di Nona",
	"Ponte Di Piave",
	"Ponte Felcino",
	"Ponte Galeria",
	"Ponte Gardena-Laion",
	"Ponte Ginori",
	"Ponte In Valtellina",
	"Ponte Nelle Alpi Polpet",
	"Ponte Pattoli",
	"Ponte S.marco-Calcinato",
	"Ponte S.pietro",
	"Ponte S.stefano",
	"Ponte Schiavo",
	"Ponte Valleceppi",
	"Pontebba",
	"Pontecagnano",
	"Pontecchio Marconi",
	"Pontecurone",
	"Pontedera Casciana Terme",
	"Pontelagoscuro",
	"Pontenure",
	"Pontetto",
	"Ponti",
	"Ponticino",
	"Pontida",
	"Pontremoli",
	"Popolano Di Marradi",
	"Popoli Vittorito",
	"Populonia",
	"Porcari",
	"Pordenone",
	"Porretta Terme",
	"Portacomaro",
	"Portici-Ercolano",
	"Porto Ceresio",
	"Porto d'Ascoli",
	"Porto Di Vasto",
	"Porto Empedocle",
	"Porto Empedocle Succursale",
	"Porto Recanati",
	"Porto S.elpidio",
	"Porto S.giorgio Fermo",
	"Porto Torres",
	"Porto Torres Marittima",
	"Porto Valtravaglia",
	"Portogruaro Caorle",
	"Portomaggiore",
	"Possidente",
	"Postioma",
	"Potenza Centrale",
	"Potenza Macchia Romana",
	"Potenza Picena Montelupone",
	"Potenza Superiore",
	"Potenza Universita'",
	"Povo-Mesiano",
	"Pozzallo",
	"Pozzolo Formigaro",
	"Pozzuoli Solfatara",
	"Pozzuolo Martesana",
	"Pracchia",
	"Praja Ajeta Tortora",
	"Prasco Cremolino",
	"Prata Camportaccio",
	"Prata Pratola",
	"Pratignone",
	"Prato Borgonuovo",
	"Prato Centrale",
	"Prato Porta Al Serraglio",
	"Prato Sesia",
	"Pratola Peligna",
	"Pratola Peligna Superiore",
	"Pre'-Saint-Didier",
	"Preganziol",
	"Pregnana Milanese",
	"Premosello Chiovenda",
	"Pretola",
	"Prezza",
	"Primolano",
	"Priola",
	"Priolo Melilli",
	"Priverno Fossanova",
	"Quarona",
	"Quarto d'Altino",
	"Quarto Di Marano",
	"Quattro Venti",
	"Quattro Ville",
	"Quercianella-Sonnino",
	"Quero Vas",
	"Quiliano-Vado Ligure",
	"Racalmuto",
	"Racconigi",
	"Ragusa",
	"Ragusa Ibla",
	"Raiano",
	"Ramazzano",
	"Ranchi",
	"Rapallo",
	"Rapolano Terme",
	"Rastignano",
	"Ravenna",
	"Recale",
	"Recco",
	"Redipuglia",
	"Reggio Calabria Aeroporto",
	"Reggio Di Calabria Archi",
	"Reggio Di Calabria Bocale",
	"Reggio Di Calabria Catona",
	"Reggio Di Calabria Centrale",
	"Reggio Di Calabria Gallico",
	"Reggio Di Calabria Lido",
	"Reggio Di Calabria Omeca",
	"Reggio Di Calabria Pellaro",
	"Reggio Di Calabria Pentimele",
	"Reggio Di Calabria S.caterina",
	"Reggio Di Calabria S.gregorio",
	"Reggio Emilia",
	"Reggio Emilia Av Mediopadana",
	"Remanzacco",
	"Remedello Sopra",
	"Remedello Sotto",
	"Renate-Veduggio",
	"Resana",
	"Rho",
	"Rho Fiera",
	"Riace",
	"Riardo-Pietramelara",
	"Ricadi-Capo Vaticano",
	"Riccione",
	"Ridotti-Collepiano",
	"Rieti",
	"Rignano sull'Arno Reggello",
	"Rigoli",
	"Rigomagno",
	"Rigoroso",
	"Rimini",
	"Rimini Miramare",
	"Rimini Torre Pedrera",
	"Rimini Viserba",
	"Riminifiera",
	"Rio Di Pusteria",
	"Riola",
	"Riomaggiore",
	"Rionero Atella Ripacandida",
	"Ripabottoni S.elia",
	"Ripafratta",
	"Riparbella",
	"Risano",
	"Riva Trigoso",
	"Rivalta Scrivia",
	"Rivarolo",
	"Rivisondoli-Pescocostanzo",
	"Robbio",
	"Robecco-Pontevico",
	"Robilante",
	"Rocca d'Evandro-S.vittore",
	"Rocca Di Corno",
	"Rocca Di Fondi",
	"Rocca Imperiale",
	"Rocca Ravindola",
	"Roccabernarda",
	"Roccalumera Mandanici",
	"Roccapalumba-Alia",
	"Roccaraso",
	"Roccasecca",
	"Roccastrada",
	"Roccavione",
	"Roccavivi",
	"Roccella",
	"Roccella Jonica",
	"Rocchetta Cairo",
	"Rocchetta S.antonio-Lacedonia",
	"Rocchetta Tanaro-Cerro",
	"Rodallo",
	"Rolo Novi Fabbrico",
	"Roma Aurelia",
	"Roma Balduina",
	"Roma Monte Mario",
	"Roma Nomentana Ll",
	"Roma Nomentana Lm",
	"Roma Ostiense",
	"Roma Prenestina",
	"Roma S.filippo Neri",
	"Roma S.pietro",
	"Roma Termini",
	"Roma Tiburtina",
	"Roma Trastevere",
	"Roma Tuscolana",
	"Romagnano Sesia",
	"Romagnano-Vietri-Salvitelle",
	"Romano",
	"Romanore",
	"Rometta Messinese",
	"Roncegno Bagni-Marter",
	"Ronchi Dei Legionari Nord",
	"Ronco Scrivia",
	"Ronta",
	"Rosa'",
	"Rosarno",
	"Roseto Capo Spulico",
	"Roseto Degli Abruzzi",
	"Rosignano",
	"Rosolina",
	"Rosolini",
	"Rossano",
	"Rossano Veneto",
	"Rossiglione",
	"Rosta",
	"Rottofreno",
	"Rovasenda",
	"Rovasenda Alta",
	"Rovato",
	"Roverbella",
	"Rovereto",
	"Roviano",
	"Rovigliano",
	"Rovigo",
	"Rubiera",
	"Rudalza",
	"Rufina",
	"Russi",
	"S.agapito Longano",
	"S.agata Di Militello",
	"S.agata Sul Santerno",
	"S.alessio Siculo-Forza d'Agro'",
	"S.ambrogio",
	"S.andrea Dello Jonio",
	"S.anna Di Chioggia",
	"S.anna Robella",
	"S.antimo-S.arpino",
	"S.antonino Di Saluggia",
	"S.antonino Vaie",
	"S.antonio Mantovano",
	"S.bartolomeo-Resina",
	"S.benedetto Del Tronto",
	"S.benedetto Sambro-Castiglione Pepoli",
	"S.benigno",
	"S.biagio",
	"S.biagio Di Callalta",
	"S.bonifacio",
	"S.candido",
	"S.cassiano",
	"S.cassiano Valchiavenna",
	"S.cataldo",
	"S.caterina Dello Jonio",
	"S.claudio",
	"S.cristina E Bissone",
	"S.cristoforo Al Lago-Ischia",
	"S.croce Del Lago",
	"S.damiano d'Asti",
	"S.demetrio De' Vestini",
	"S.domenica",
	"S.dona' Di Piave-Jesolo",
	"S.donato Milanese",
	"S.donnino Badia",
	"S.elena-Este",
	"S.ellero",
	"S.eurosia",
	"S.felice Sul Panaro",
	"S.filippo",
	"S.flavia-Solunto-Porticello",
	"S.frediano A Settimo",
	"S.gavino",
	"S.gennaro",
	"S.germano Vercellese",
	"S.giacomo Di Teglio",
	"S.giorgio",
	"S.giorgio Casale",
	"S.giorgio Delle Pertiche",
	"S.giorgio Di Nogaro",
	"S.giorgio Di Piano",
	"S.giovanni Al Natisone",
	"S.giovanni Di Casarsa",
	"S.giovanni In Croce",
	"S.giovanni In Persiceto",
	"S.giovanni Valdarno",
	"S.giuletta",
	"S.giuliano Milanese",
	"S.giuliano Piacentino",
	"S.giuliano Piemonte",
	"S.giuliano Terme",
	"S.giuseppe Di Cairo",
	"S.giustina-Cesio",
	"S.giustino",
	"S.ilario d'Enza",
	"S.lazzaro Di Savena",
	"S.liberato",
	"S.lorenzo",
	"S.lorenzo Maggiore",
	"S.lucido Marina",
	"S.marcellino Frignano",
	"S.marco d'Alunzio-Torrenova",
	"S.marco Roggiano",
	"S.marco Vecchio",
	"S.margherita Ligure Portofino",
	"S.maria Capua Vetere",
	"S.maria Delle Mole",
	"S.maria La Bruna",
	"S.maria La Longa",
	"S.marinella",
	"S.marino",
	"S.martino Al Cimino",
	"S.martino Buonalbergo",
	"S.martino Cava",
	"S.martino Di Lupari",
	"S.martino In Campo",
	"S.martino In Gattara",
	"S.maurizio Canavese",
	"S.michele",
	"S.michele Di Serino",
	"S.michele In Bosco",
	"S.miniato Fucecchio",
	"S.momme'",
	"S.nazario",
	"S.nicola Tonnara",
	"S.nicolo",
	"S.paolo Solbrito",
	"S.patrizio",
	"S.piero A Sieve",
	"S.pietro A Maida-Maida",
	"S.pietro A Vico",
	"S.pietro Avellana-Capracotta",
	"S.pietro Berbenno",
	"S.pietro In Casale",
	"S.pietro In Gu'",
	"S.pietro Vernotico",
	"S.romano-Montopoli-S.croce",
	"S.sebastiano Po",
	"S.severa",
	"S.severino Marche",
	"S.severo",
	"S.stefano Belbo",
	"S.stefano Di Camastra-Mistretta",
	"S.stefano Di Magra",
	"S.stefano Lodigiano",
	"S.stefano Udinese",
	"S.stino Di Livenza",
	"S.teresa Di Riva",
	"S.teresa Longarini",
	"S.trovaso",
	"S.vincenzo",
	"S.vincenzo Valle Roveto",
	"S.vito Al Tagliamento",
	"S.vito Dei Normanni",
	"S.vito Lanciano",
	"S.vittoria",
	"S.zeno Folzano",
	"S.zenone Al Lambro",
	"Sacile",
	"Sacile S.liberale",
	"Sagrado",
	"Saint-Pierre",
	"Sairano",
	"Sairano Zinasco",
	"Sala Al Barro-Galbiate",
	"Salandra-Grottole",
	"Salbertrand",
	"Sale Langhe",
	"Salemi Gibellina",
	"Salerno",
	"Salerno Irno",
	"Saletto",
	"Saliceto",
	"Saline Di Reggio",
	"Salone",
	"Salorno",
	"Salsomaggiore Terme",
	"Saluggia",
	"Salussola",
	"Saluzzo",
	"Salzano Robegano",
	"Samassi Serrenti",
	"Samoggia",
	"Samolaco",
	"Sampieri",
	"San Faustino-Casigliano",
	"San Gottardo",
	"San Paolo",
	"San Polo Matese",
	"Sandigliano",
	"Sanfre`",
	"Sangemini",
	"Sangiano",
	"Sanguinetto",
	"Sanluri Stato",
	"Sannazzaro",
	"Sanremo",
	"Sansecondo",
	"Sansepolcro",
	"Santarcangelo Di Romagna",
	"Sante Marie",
	"Santeramo",
	"Santhia'",
	"Santopadre",
	"Santuario",
	"Sapri",
	"Sarmato",
	"Sarno",
	"Sarre",
	"Sartirana",
	"Sarzana",
	"Sassa Tornimparte",
	"Sassari",
	"Sasso Marconi",
	"Sassoferrato Arcevia",
	"Sassone",
	"Savigliano",
	"Savignano Greci",
	"Savignano Sul Rubicone",
	"Savona",
	"Scafa S.valentino-Caramanico Terme",
	"Scafati",
	"Scalea S.domenica Talao",
	"Scaletta Zanclea",
	"Scanzano Jonico-Montalbano Jonico",
	"Scarlino",
	"Scerne Di Pineto",
	"Schio",
	"Scicli",
	"Scilla",
	"Scopeti",
	"Scorcetoli",
	"Scordia",
	"Scurcola Marsicana",
	"Secugnago",
	"Sedico Bribano",
	"Segesta Tempio",
	"Segrate",
	"Selci Lama",
	"Sella Di Corno",
	"Sellia Marina",
	"Senigallia",
	"Seregno",
	"Serenissima",
	"Seriate",
	"Serino",
	"Serra S.quirico",
	"Serradifalco",
	"Serralunga Cereseto",
	"Serramanna Nuraminis",
	"Serravalle all'Adige",
	"Serravalle d'Asti",
	"Serravalle Pistoiese",
	"Serravalle Scrivia",
	"Sessa Aurunca-Roccamonfina",
	"Sessano Del Molise",
	"Sesto Calende",
	"Sesto Campano",
	"Sesto Fiorentino",
	"Sesto S.giovanni",
	"Sestri Levante",
	"Settebagni",
	"Settequerce",
	"Settime Cinaglio Mombarone",
	"Settimo",
	"Settingiano",
	"Sevegliano",
	"Sezzadio",
	"Sezze Romano",
	"Sgurgola",
	"Sibari",
	"Sicignano Degli Alburni",
	"Siderno",
	"Sieci",
	"Siena",
	"Siena Zona Industriale",
	"Signa",
	"Siliqua",
	"Silla",
	"Sillavengo",
	"Silvi",
	"Simeri Crichi",
	"Sinalunga",
	"Sipicciano",
	"Sipicciano S.nicola",
	"Siponto",
	"Siracusa",
	"Sistiana-Visogliano",
	"Sizzano",
	"Soffratta",
	"Solagna",
	"Solarolo",
	"Solarussa",
	"Solero",
	"Solfagnano-Parlesca",
	"Solignano",
	"Solofra",
	"Solopaca",
	"Somma Lombardo",
	"Sommariva Del Bosco",
	"Sondrio",
	"Sora",
	"Soresina",
	"Sorgenti Del Peschiera",
	"Sori",
	"Soverato",
	"Spadafora",
	"Spagnuola",
	"Sparanise",
	"Spello",
	"Spezzano Albanese Terme",
	"Spigno",
	"Spinazzola",
	"Spinea",
	"Spinetoli Colli",
	"Spinetoli Villa S.pio X",
	"Spinetta",
	"Spoleto",
	"Spotorno Noli",
	"Spresiano",
	"Squillace",
	"Squinzano",
	"St.dalmas De Tende",
	"Stabio",
	"Stanghella",
	"Stazione Per l'Alpago",
	"Stezzano",
	"Sticciano",
	"Stimigliano",
	"Strada Casale",
	"Stradella",
	"Strambino",
	"Strassoldo",
	"Stresa",
	"Strevi",
	"Strigno",
	"Strongoli",
	"Su Canale",
	"Sulmona",
	"Sulmona S.rufina",
	"Sulmona-Introdacqua",
	"Suno",
	"Susa",
	"Susegana",
	"Suzzara",
	"Taggia Arma",
	"Tagliacozzo",
	"Taino Angera",
	"Talamona",
	"Talamone",
	"Taormina-Giardini",
	"Taranto",
	"Tarcento",
	"Targia",
	"Tarquinia",
	"Tarsia",
	"Tarvisio Boscoverde",
	"Tassignano-Capannori",
	"Tavazzano",
	"Teano",
	"Teglio Veneto",
	"Telese Cerreto",
	"Tempio Di Vulcano",
	"Tende",
	"Teramo",
	"Terlano-Andriano",
	"Terme Euganee-Abano-Montegrotto",
	"Terme Vigliatore",
	"Termini Imerese",
	"Termoli",
	"Ternate Varano Borghi",
	"Terni",
	"Terni Borgo Rivo",
	"Terni Cospea",
	"Terno",
	"Terontola Cortona",
	"Terracina",
	"Terrenove",
	"Terzo Montabone",
	"Tezze Di Grigno",
	"Thiene",
	"Tione Degli Abruzzi",
	"Tirano",
	"Tito",
	"Tivoli",
	"Tocco Castiglione",
	"Todi Ponte Naia",
	"Todi Ponte Rio",
	"Tolentino",
	"Tolentino Campus",
	"Tollo Canosa Sannita",
	"Tonco Alfiano",
	"Tor Sapienza",
	"Tor Vergata",
	"Tora Presenzano",
	"Torano Lattarico",
	"Torino Aeroporto Di Caselle",
	"Torino Corso Grosseto",
	"Torino Lingotto",
	"Torino Porta Nuova",
	"Torino Porta Susa",
	"Torino Rebaudengo Fossata",
	"Torino Stura",
	"Torrazza Piemonte",
	"Torre Annunziata Centrale",
	"Torre Annunziata Citta'",
	"Torre De' Picenardi",
	"Torre Dei Passeri",
	"Torre Del Greco",
	"Torre Del Lago Puccini",
	"Torre In Pietra-Palidoro",
	"Torre Melissa",
	"Torre Orsaia",
	"Torre Pellice",
	"Torreberetti",
	"Torregrotta",
	"Torremezzo Di Falconara",
	"Torricella",
	"Torricola",
	"Torrile S.polo",
	"Torrione",
	"Torrita Di Siena",
	"Tortona",
	"Tortoreto Lido",
	"Toscano",
	"Trabia",
	"Traccia",
	"Trani",
	"Trapani",
	"Trappa",
	"Trappeto",
	"Travedona Biandronno",
	"Travesio",
	"Tre Croci",
	"Trebaseleghe",
	"Trebbio",
	"Trebisacce",
	"Trecate",
	"Trecella",
	"Tremestieri",
	"Trento",
	"Trento S.bartolameo",
	"Trento S.chiara",
	"Trepuzzi",
	"Tresenda-Aprica-Teglio",
	"Trestina",
	"Trevi",
	"Treviglio",
	"Treviglio Ovest",
	"Trevignano Signoressa",
	"Treviso Centrale",
	"Trezzano Sul Naviglio",
	"Tricesimo-S.pelagio",
	"Trieste Airport",
	"Trieste Centrale",
	"Trinita' Bene Vagienna",
	"Trinitapoli-S.ferdinando Di Puglia",
	"Trino Vercellese",
	"Triuggio-Ponte Albiate",
	"Trivigno",
	"Trofarello",
	"Tromello",
	"Tronzano",
	"Tropea",
	"Tufo",
	"Tuoro Sul Trasimeno",
	"Tusa",
	"Udine",
	"Ugovizza Valbruna",
	"Umbertide",
	"Uras Mogoro",
	"Urbisaglia Sforzacosta",
	"Vada",
	"Vaglia",
	"Vaiano",
	"Vaio Ospedale",
	"Vairano-Caianello",
	"Val d'Ala",
	"Valdaora-Anterselva",
	"Valenza",
	"Valle Aurelia",
	"Valle dell'Aniene-Mandela-Sambuci",
	"Valle Di Maddaloni Pes",
	"Valle Di Mercato S.severino",
	"Valle Lomellina",
	"Vallecrosia",
	"Valledolmo",
	"Vallelunga",
	"Vallo Della Lucania-Castelnuovo",
	"Valmadonna",
	"Valmadrera",
	"Valmontone",
	"Valtopina",
	"Vandoies",
	"Vanzago Pogliano",
	"Vaprio d'Agogna",
	"Varallo Pombia",
	"Varallo Sesia",
	"Varano",
	"Varazze",
	"Varenna Esino",
	"Varese",
	"Varignana",
	"Vasto S.salvo",
	"Vastogirardi",
	"Velletri",
	"Venafro",
	"Venaria Reale Reggia",
	"Venaria Reale Rigola Stadio",
	"Venezia Carpenedo",
	"Venezia Mestre",
	"Venezia Mestre Gazzera",
	"Venezia Mestre Olimpia",
	"Venezia Mestre Ospedale",
	"Venezia Porto Marghera",
	"Venezia S.lucia",
	"Ventimiglia",
	"Venzone",
	"Verbania-Pallanza",
	"Verceia",
	"Vercelli",
	"Vercurago S.girolamo",
	"Verdello Dalmine",
	"Vergato",
	"Vergiate",
	"Vergnasco",
	"Vernante",
	"Vernazza",
	"Vernio Montepiano Cantagallo",
	"Verolanuova",
	"Verolengo",
	"Verona Porta Nuova",
	"Verona Porta Vescovo",
	"Verres",
	"Verzuolo",
	"Vespolate",
	"Vetralla",
	"Vezzano Ligure",
	"Viadana Bresciana",
	"Viareggio",
	"Vibo Marina",
	"Vibo Valentia-Pizzo",
	"Vicchio",
	"Vicenza",
	"Vicofertile",
	"Vicoforte S.michele",
	"Vicovaro",
	"Vidalengo",
	"Vietri Sul Mare-Amalfi",
	"Vievola",
	"Vigevano",
	"Vigliano Candelo",
	"Vigliano d'Asti",
	"Vigna Clara Pes",
	"Vigna Di Valle",
	"Vignale",
	"Vignale Riotorto",
	"Vignate",
	"Vigodarzere",
	"Vigonza Pianiga",
	"Villa Bonelli",
	"Villa Claudia",
	"Villa Del Conte",
	"Villa Di Tirano",
	"Villa Literno",
	"Villa Opicina",
	"Villa Pitignano",
	"Villa Raverio",
	"Villa S.giovanni",
	"Villa S.giovanni Cannitello",
	"Villa S.michele",
	"Villa S.sebastiano",
	"Villabartolomea",
	"Villabassa-Braies-Val Di Braies",
	"Villadossola",
	"Villafranca Di Verona",
	"Villafranca Tirrena-Saponara",
	"Villafranca-Bagnone",
	"Villafranca-Cantarana",
	"Villalba",
	"Villamaggiore",
	"Villamassargia Domusnovas",
	"Villanova Canavese-Grosso",
	"Villanova d'Arda",
	"Villanova d'Ardenghi",
	"Villanova d'Asti",
	"Villanova Di Reggiolo",
	"Villapiana Lido",
	"Villapiana Torre Cerchiara",
	"Villarosa",
	"Villasanta Parco",
	"Villasor",
	"Villaspeciosa Uta",
	"Villastellone",
	"Villaverla Montecchio",
	"Villazzano",
	"Villeneuve",
	"Villetta",
	"Villetta Malagnino",
	"Villetta S.romano",
	"Vilpiano-Nalles",
	"Vinchiaturo",
	"Vipiteno-Val Di Vizze",
	"Visano",
	"Visone",
	"Viterbo Porta Fiorentina",
	"Viterbo Porta Romana",
	"Vittoria",
	"Vittorio Veneto",
	"Vittuone Arluno",
	"Vitulano Foglianise",
	"Vizzini-Licodia",
	"Voghera",
	"Vogogna Ossola",
	"Volpiano",
	"Voltana",
	"Volterra Saline-Pomarance",
	"Zagarolo",
	"Zambra",
	"Zambrone",
	"Zappulla",
	"Zinasco Nuovo",
	"Zoagli",
];
